#!/bin/bash
#
# chkconfig: 345 29 73
# description: mount/unmount my custom bind mounts onto external hdd
#
#
### BEGIN INIT INFO
# Provides:
### END INIT INFO

. /etc/init.d/functions

ROOTFS=`blkid |grep XSCE-RootOverlay|awk '{split($0,a,"\""); print a[2]}'`
ROOTOVL=`grep LABEL=XSCE-RootOverlay /etc/fstab|awk '{split($0,a," "); print a[1]}'`

# Don't do the mounts if the external drive labelled XSCE-RootOverlay is not present
# And if it is not, reset fstab and reboot; otherwise networking fails
# If it is present and fstab does not have XSCE-RootOverlay, fix up fstab and reboot

if  [ "$ROOTFS" != "XSCE-RootOverlay" ] ; then
  logger "$0 - No XSCE-RootOverlay drive attached"
  if [ "$ROOTOVL" == "LABEL=XSCE-RootOverlay" ] ; then
    logger "$0 - Resetting fstab to original"
    cp /etc/fstab.ORIG /etc/fstab
    reboot
  fi
  exit 1
elif [ "$ROOTOVL" != "LABEL=XSCE-RootOverlay" ] ; then
  logger "$0 - Setting fstab to mount external hdd"
  cat /etc/fstab.hddmnt >> /etc/fstab
  reboot
fi 

case "$1" in
  start)
        # Other mounts are done in fstab
        # These don't work there
        logger "$0 - Bind Mounting /usr and /tmp"
        /bin/mount --bind /mnt/extdrv/usr /usr
        /bin/mount --bind /mnt/extdrv/tmp /tmp
        ;;

  stop)
        /bin/umount /usr
        /bin/umount /tmp
        ;;

  status)
        ;;

  restart)
        $0 stop
        $0 start
        ;;

  reload)
        $0 start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0

