#!/bin/bash
# xsce-hddctl - enable or disable mounting of hdd with label RootOverlay

ROOTFS=`blkid |grep XSCE-RootOverlay|awk '{split($0,a,"\""); print a[2]}'`
ROOTOVL=`grep LABEL=XSCE-RootOverlay /etc/fstab|awk '{split($0,a," "); print a[1]}'`

mkdir -p /mnt/extdrv
mkdir -p /mnt/mmc

mount /dev/mmcblk0p3 /mnt/mmc

if  [ "$ROOTFS" == "XSCE-RootOverlay" ] ; then
  mount -L XSCE-RootOverlay /mnt/extdrv
fi 
case "$1" in
  enable)              
        if [ "$ROOTFS" != "XSCE-RootOverlay" ] ; then
          echo "External HDD with XSCE-RootOverlay not found."
          echo "You can either attach a prepared drive or run xsce-prepdisk to format one."
          exit 1   
        fi
        if [ "$ROOTOVL" == "LABEL=XSCE-RootOverlay" ] ; then
          echo "Looks to be enabled already."
          echo "Exiting."
          exit 1   
        fi
        cp /mnt/mmc/etc/fstab.ORIG /mnt/mmc/etc/fstab
        cat /mnt/mmc/etc/fstab.hddmnt >> /mnt/mmc/etc/fstab
        cp /mnt/mmc/etc/fstab.* /mnt/extdrv/etc       
        cp -f 010-xsce-extmnt /mnt/mmc/etc/rc.d/init.d
        cp -f 010-xsce-extmnt /mnt/extdrv/etc/rc.d/init.d
        echo "Rebooting"
        reboot
        ;;

  disable)
        if [ "$ROOTFS" == "XSCE-RootOverlay" ] ; then
          cp /mnt/mmc/fstab.ORIG /mnt/extdrv/etc/fstab
          rm -f /mnt/extdrv/etc/rc.d/init.d/010-xsce-extmnt   
        fi             
        cp /mnt/mmc/etc/fstab.ORIG /mnt/mmc/etc/fstab
        rm -f /mnt/mmc/etc/rc.d/init.d/010-xsce-extmnt
        echo "Rebooting"
        reboot
        ;;

  *)
        echo $"Usage: $0 {enable|disable}"
        exit 1
esac

exit 0

